services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - 3032:80
    volumes:
      - ./backend:/app
      - fastapi-sample:/app/.venv
    working_dir: /app
    command: bash -c "poetry install && poetry run task dev"
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    environment:
      - BACKEND_DOMAIN=fastapi
    volumes:
      - ./frontend:/app
      - nextjs-node-modules:/app/node_modules
    ports:
      - 80:3000
    depends_on:
      - backend
    working_dir: /app
    command: bash -c "npm install && npm run dev"
  postgres-server:
    image: postgres:latest
    environment:
      - POSTGRES_DATABASE=pokemon
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432
    volumes:
      - ./database/sql:/docker-entrypoint-initdb.d # docker-entrypoint-initdb.d内のスクリプトは起動時に1度だけ実行される

volumes:
  fastapi-sample:
  nextjs-node-modules:
  postgres-server:
